# -*- coding: utf-8 -*-
# Modified by Kamirul Kamirul
# Contact: kamirul.apr@gmail.com

# Original implementation by Peize Sun, Rufeng Zhang
# Contact: {sunpeize, cxrfzhang}@foxmail.com

# Copyright (c) Facebook, Inc. and its affiliates. All Rights Reserved
from detectron2.config import CfgNode as CN

def add_rsparsercnn_config(cfg):
    """
    Add config for SparseRCNN.
    """
    cfg.MODEL.RSparseRCNN = CN()
    cfg.MODEL.RSparseRCNN.NUM_CLASSES = 1
    cfg.MODEL.RSparseRCNN.NUM_PROPOSALS = 100

    # RCNN Head.
    cfg.MODEL.RSparseRCNN.NHEADS = 8 #self_attn
    cfg.MODEL.RSparseRCNN.DROPOUT = 0.0
    cfg.MODEL.RSparseRCNN.DIM_FEEDFORWARD = 2048
    cfg.MODEL.RSparseRCNN.ACTIVATION = 'relu'
    cfg.MODEL.RSparseRCNN.HIDDEN_DIM = 256
    cfg.MODEL.RSparseRCNN.NUM_CLS = 1
    cfg.MODEL.RSparseRCNN.NUM_REG = 3
    cfg.MODEL.RSparseRCNN.NUM_HEADS = 6 #6

    # Dynamic Conv.
    cfg.MODEL.RSparseRCNN.NUM_DYNAMIC = 2
    cfg.MODEL.RSparseRCNN.DIM_DYNAMIC = 64

    # Loss.
    cfg.MODEL.RSparseRCNN.CLASS_WEIGHT = 2.0
    cfg.MODEL.RSparseRCNN.IOU_WEIGHT = 2.0
    cfg.MODEL.RSparseRCNN.L1_WEIGHT = 5.0
    cfg.MODEL.RSparseRCNN.DEEP_SUPERVISION = True
    cfg.MODEL.RSparseRCNN.NO_OBJECT_WEIGHT = 0.1

    # Focal Loss.
    cfg.MODEL.RSparseRCNN.USE_FOCAL = True
    cfg.MODEL.RSparseRCNN.ALPHA = 0.25
    cfg.MODEL.RSparseRCNN.GAMMA = 2.0
    cfg.MODEL.RSparseRCNN.PRIOR_PROB = 0.01

    # Optimizer.
    cfg.SOLVER.OPTIMIZER = "ADAMW"
    cfg.SOLVER.BACKBONE_MULTIPLIER = 1.0
    cfg.SOLVER.AMSGRAD = "False"

    # Dataset Labels
    cfg.CLASS_LABELS = ["ship"]
    
    # =============================================
    # NASTaR Dataset Configuration
    # =============================================
    cfg.TRAIN_DATASET_NAME = "NASTaR_train"
    cfg.EVAL_DATASET_NAME = "NASTaR_val"
    cfg.DATASET_NAME = "NASTaR"

    # Root of the extracted NASTaR dataset (contains Data/ folder)
    cfg.DATASET_MAIN_DIR = "./2tfa6x37oerz2lyiw6hp47058"

    # For evaluation, images are resolved relative to DATASET_MAIN_DIR
    cfg.EVAL_IMAGES_DIR = "./2tfa6x37oerz2lyiw6hp47058"

    # Path to the evaluation and training JSONs (generated by the conversion script)
    cfg.EVAL_JSON_PATH = "eval_json/NASTaR_test_COCO_OBB_Detectron.json"
    cfg.TRAIN_JSON_PATH = "eval_json/NASTaR_train_COCO_OBB_Detectron.json"